#! /bin/sh

if [ $# != 1 ]
then
	echo "usage: install-common mode"
	exit 1
fi

db_mode=$1
host=`hostname -s`

case $db_mode in
dev | test)
	user=`id -un`
	conf_key=${user}-${db_mode}
	;;
production)
	conf_key=${db_mode}
	;;
*)
	echo "invalid db_mode $db_mode"
	exit 1
	;;
esac


db_name=dpmt-${conf_key}
apache_conf_dir=/etc/apache2/conf.d
apachectl_cmd=apache2ctl
site_root=/var/www/html/zorky-${conf_key}
apache_conf=zorky-${host}-${conf_key}.conf
aux_dir=/var/zorky-${conf_key}

if [ $db_mode = production ]
then
    make -q
    if [ $? != 0 ]
    then
	echo "you need to run make"
	exit 1
    fi
else
    make
fi

mkdir -p ${site_root}

rm -f ${site_root}/zorky-conf.php
cat > ${site_root}/zorky-conf.php <<!
<?php
  global \$db_name, \$site_root, \$conf_key, \$aux_dir;
  \$db_name = '${db_name}';
  \$site_root = '${site_root}';
  \$conf_key = '${conf_key}';
  \$aux_dir = '${aux_dir}';
?>
!


cmp -s $apache_conf $apache_conf_dir/$apache_conf
if [ $? != 0 ]
then
	echo "need apache conf update ... run this as root:"
	echo ""
	echo "cp $apache_conf $apache_conf_dir/. ; $apachectl_cmd graceful"
	exit 1
fi

mkdir -p -m 777 ${aux_dir}/tmp
mkdir -p ${aux_dir}/bin
mkdir -p ${aux_dir}/z5

if [ "$db_mode" = "production" ]
then
    rsync -t -i --files-from=SITE-FILES . ${site_root}/.

    install -c -m 755 run-dfrotz ${aux_dir}/bin/.
else
    for f in `cat SITE-FILES`
    do
	rm -f ${site_root}/${f}
	ln -s `pwd`/$f ${site_root}/${f}
    done

    dir=`pwd`
    ln -sf $dir/run-dfrotz ${aux_dir}/bin/.
fi

if [ ! -x ../frotz-2.43/dfrotz ]
then
    echo "do make dumb in frotz first"
    exit 1
fi
install -c -m 755 ../frotz-2.43/dfrotz ${aux_dir}/bin/.
cp ../z5/* ${aux_dir}/z5/.
